version: '3'
services:
  db:
    image: postgres:latest
    container_name: sparkify
    environment:
      POSTGRES_DB: sparkifydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      # user for healthcheck
      PGUSER: postgres
    # check that database is ready
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - 5432:5432
  pipeline:
    build: .
    volumes:
      - ./data:/pipeline/data
    depends_on:
      db:
        # wait for database to be ready
        condition: service_healthy
